### PR TITLE
Increased some font sizes

### PR DESCRIPTION
**Pull request by jschultz**
In response to issue #55 this PR increases some of the font sizes. Notably the base font for tweet text changes from fontSizeExtraSmall to fontSizeSmall, which seems to better reflect the guidelines mentioned here: [https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-theme.html/#fontSizeSmall-prop](https://sailfishos.org/develop/docs/silica/qml-sailfishsilica-sailfish-silica-theme.html/#fontSizeSmall-prop)

Note that these changes are a bit ad hoc, since I'm not familiar with all the QML files and how they are used. Still they make piepmatz look much nicer to me.

### CODE REVIEW

**Comment by Wunderfitz** [comment]
Sorry for the late answer. In general, I'm open to such a change, but in this case it should be configurable and the default should be the existing setting/configuration. Your PR would change the default configuration - which I intentionally implemented the way it is at the moment.

Please see https://github.com/Wunderfitz/harbour-piepmatz/blob/master/src/accountmodel.cpp and https://github.com/Wunderfitz/harbour-piepmatz/blob/master/qml/pages/SettingsPage.qml about existing examples.

**Comment by raketti** [comment]
I have to agree with @jschultz about the font size. The Silica docs state the following for the UI text size:
`Theme.fontSizeMedium` - the most common text size; this is the default font size of Label and most UI controls
So this should be the main tweet font size and captions should be:
`Theme.fontSizeSmall` - for general secondary text or paragraphs of non-interactive text

So for example in https://github.com/Wunderfitz/harbour-piepmatz/blob/15ea6d2f44bae6af8fc4304c666e481cca327167/qml/pages/TweetPage.qml#L185-L189

`font.pixelSize: Theme.fontSizeExtraSmall` should be `font.pixelSize: Theme.fontSizeMedium`

**Comment by Wunderfitz** [comment]
@raketti That label is actually a bad example as this is just a trick to get some space after the last UI element of the component. Probably, I should do this better anyway. ;) 

But back to topic  - the PR itself already addresses (most of) the affected definitions (such as https://github.com/Wunderfitz/harbour-piepmatz/blob/master/qml/components/TweetText.qml#L45), but I definitely won't change it in general as IMHO Sailfish OS and many stock apps waste an insanely high amount of precious space - also related to the crazy big font sizes - and the UX guidelines also support that. I didn't want to have it here in my app, that's why I made everything more compact - and the default will remain that way.

However, I have nothing against a setting which increases the font size on demand and specific for Piepmatz. So if the PR is changed accordingly, the merge will happen. If not, I'll probably implement it myself in one of the next releases.

**Comment by raketti** [comment]
Ok, I can understand your point. I'd really much like to see a font size feature.

Unfortunately my coding skills are close to zero. I could take a look as an educational hobby.. :)

**Comment by jschultz** [comment]
Yeah sorry I haven't followed up this PR. I've been too busy and my only Sailfish device (Xperia X) was out of service with a broken screen for several months.

Regarding the general discussion, would it not be more consistent for piepmatz to respect Sailfish UI guidelines and for users who prefer a more compact font to adjust them using Sailfish settings (and then to get more compact fonts across all applications)?

Personally my eyesight is simply not good enough to read tweets as the code stands, at least on my device.

**Comment by Wunderfitz** [comment]
Finally done with 639b483b00f62dedf7da2f397c6c64f80c723666. Sorry for closing this one, but as mentioned at the beginning, this one will only be introduced as setting. Will be in version 1.4. :)

**Pull request closed without merging**
